name: Deploy to production

on:
    push:
        branches: [master]
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        logout: true

    - name: Build image
      run: docker build -t 322810/buss .
    - name: Tag image
      run: docker tag 322810/buss 322810/buss:latest
    - name: Push to dockerhub
      run: docker push 322810/buss

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: buss
        environment_name: Buss-env
        region: eu-north-1